import { MaterialCommunityIcons } from '@expo/vector-icons';
import { StyleSheet, Text, View } from 'react-native';
import { AppCard } from '../../components/AppCard';
import { Screen } from '../../components/Screen';
import { colors, radius, spacing, typography } from '../../theme';

export function MarketScreen() {
  return <Screen title="댕마켓" subtitle="보리에게 꼭 맞는 산책 아이템을 찾아보세요."><View style={styles.banner}><View style={styles.bannerCopy}><Text style={styles.bannerEyebrow}>AUTUMN WALK</Text><Text style={styles.bannerTitle}>가을 산책을 위한{`\n`}필수 아이템</Text><Text style={styles.bannerBody}>따뜻하고 안전한 산책 준비</Text></View><MaterialCommunityIcons name="dog" size={72} color={colors.orange} /></View><View style={styles.categories}>{['식품', '간식', '건강', '용품', '패션'].map((label, index) => <View key={label} style={styles.category}><View style={styles.categoryIcon}><MaterialCommunityIcons name={['food-drumstick-outline', 'bone', 'heart-pulse', 'dog-side', 'tshirt-crew-outline'][index] as never} size={21} color={colors.forest} /></View><Text style={styles.categoryText}>{label}</Text></View>)}</View><View style={styles.sectionRow}><Text style={styles.sectionTitle}>보리에게 딱 맞아요</Text><Text style={styles.more}>전체보기</Text></View><View style={styles.products}><ProductCard title="프레쉬핏 워크 하네스" price="42,000원" icon="dog-side" /><ProductCard title="포레스트 투어 리드줄" price="28,000원" icon="link-variant" /></View><AppCard><View style={styles.notice}><MaterialCommunityIcons name="truck-fast-outline" size={24} color={colors.forest} /><View style={styles.noticeCopy}><Text style={styles.noticeTitle}>보리의 체형에 맞는 상품을 찾았어요</Text><Text style={styles.noticeBody}>반려견 프로필을 바탕으로 추천해드려요.</Text></View><MaterialCommunityIcons name="chevron-right" size={21} color={colors.inkFaint} /></View></AppCard></Screen>;
}
function ProductCard({ title, price, icon }: { title: string; price: string; icon: string }) { return <View style={styles.product}><View style={styles.productImage}><MaterialCommunityIcons name={icon as never} size={45} color={colors.forest} /></View><Text style={styles.productTitle}>{title}</Text><Text style={styles.productPrice}>{price}</Text><Text style={styles.productRating}>♡ 4.9 · 28</Text></View>; }
const styles = StyleSheet.create({ banner: { alignItems: 'center', backgroundColor: colors.orangeSoft, borderRadius: radius.lg, flexDirection: 'row', justifyContent: 'space-between', minHeight: 150, overflow: 'hidden', padding: spacing.lg }, bannerCopy: { gap: 4 }, bannerEyebrow: { color: colors.orange, ...typography.caption, fontWeight: '700' }, bannerTitle: { color: colors.ink, ...typography.heading }, bannerBody: { color: colors.inkSoft, ...typography.caption }, categories: { flexDirection: 'row', justifyContent: 'space-between' }, category: { alignItems: 'center', gap: 5 }, categoryIcon: { alignItems: 'center', backgroundColor: colors.white, borderColor: colors.line, borderRadius: 99, borderWidth: 1, height: 44, justifyContent: 'center', width: 44 }, categoryText: { color: colors.inkSoft, ...typography.caption }, sectionRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, sectionTitle: { color: colors.ink, ...typography.heading }, more: { color: colors.forest, ...typography.label }, products: { flexDirection: 'row', gap: spacing.md }, product: { flex: 1 }, productImage: { alignItems: 'center', backgroundColor: colors.ivorySoft, borderRadius: radius.md, height: 130, justifyContent: 'center' }, productTitle: { color: colors.ink, marginTop: spacing.sm, ...typography.label }, productPrice: { color: colors.ink, fontWeight: '800', marginTop: 3 }, productRating: { color: colors.inkFaint, marginTop: 2, ...typography.caption }, notice: { alignItems: 'center', flexDirection: 'row', gap: spacing.md }, noticeCopy: { flex: 1 }, noticeTitle: { color: colors.ink, ...typography.label }, noticeBody: { color: colors.inkSoft, marginTop: 2, ...typography.caption } });
