import { MaterialCommunityIcons } from '@expo/vector-icons';
import { StyleSheet, Text, View } from 'react-native';
import { AppCard } from '../../components/AppCard';
import { Screen } from '../../components/Screen';
import { colors, radius, spacing, typography } from '../../theme';

export function MapScreen() {
  return (
    <Screen title="산책 지도" subtitle="보리와 함께 걸었던 장소를 한눈에 모아보세요.">
      <View style={styles.search}><MaterialCommunityIcons name="magnify" size={20} color={colors.inkSoft} /><Text style={styles.searchText}>산책 장소나 시설을 검색해보세요</Text><MaterialCommunityIcons name="tune-variant" size={18} color={colors.forest} /></View>
      <View style={styles.filters}><Filter label="전체" active /><Filter label="사진 핀" /><Filter label="친화시설" /></View>
      <View style={styles.map}><View style={styles.water} /><View style={[styles.road, styles.roadOne]} /><View style={[styles.road, styles.roadTwo]} /><View style={[styles.pin, styles.pinOne]}><MaterialCommunityIcons name="camera" size={16} color={colors.white} /></View><View style={[styles.pin, styles.pinTwo]}><MaterialCommunityIcons name="paw" size={16} color={colors.white} /></View><View style={styles.current}><View style={styles.currentDot} /></View><View style={styles.mapLabel}><Text style={styles.mapLabelTitle}>보리와 최근 산책</Text><Text style={styles.mapLabelBody}>서울숲 · 2.31km</Text></View></View>
      <AppCard><View style={styles.cardRow}><View style={styles.iconBubble}><MaterialCommunityIcons name="storefront-outline" size={21} color={colors.forest} /></View><View style={styles.cardCopy}><Text style={styles.cardTitle}>보리와 함께 찾은 장소</Text><Text style={styles.cardBody}>반려동물과 함께 갈 수 있는 장소를 추천해드려요.</Text></View><MaterialCommunityIcons name="chevron-right" size={22} color={colors.inkFaint} /></View></AppCard>
    </Screen>
  );
}

function Filter({ label, active = false }: { label: string; active?: boolean }) { return <View style={[styles.filter, active && styles.filterActive]}><Text style={[styles.filterText, active && styles.filterTextActive]}>{label}</Text></View>; }

const styles = StyleSheet.create({ search: { alignItems: 'center', backgroundColor: colors.white, borderColor: colors.line, borderRadius: radius.md, borderWidth: 1, flexDirection: 'row', gap: spacing.sm, padding: spacing.md }, searchText: { color: colors.inkFaint, flex: 1, ...typography.caption }, filters: { flexDirection: 'row', gap: spacing.sm }, filter: { backgroundColor: colors.white, borderColor: colors.line, borderRadius: 99, borderWidth: 1, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm }, filterActive: { backgroundColor: colors.forest, borderColor: colors.forest }, filterText: { color: colors.inkSoft, ...typography.label }, filterTextActive: { color: colors.white }, map: { backgroundColor: '#DCE9DE', borderRadius: radius.lg, height: 350, overflow: 'hidden', position: 'relative' }, water: { backgroundColor: '#C8E1E4', height: 125, left: -25, position: 'absolute', right: -25, top: 105, transform: [{ rotate: '-8deg' }] }, road: { backgroundColor: '#F9F4E7', borderColor: '#B9CBB4', borderWidth: 3, borderRadius: 99, position: 'absolute' }, roadOne: { height: 230, left: 97, top: 45, transform: [{ rotate: '38deg' }], width: 24 }, roadTwo: { height: 300, right: 88, top: 12, transform: [{ rotate: '-55deg' }], width: 18 }, pin: { alignItems: 'center', backgroundColor: colors.orange, borderColor: colors.white, borderRadius: 99, borderWidth: 3, height: 38, justifyContent: 'center', position: 'absolute', width: 38 }, pinOne: { left: 105, top: 112 }, pinTwo: { right: 103, top: 196, backgroundColor: colors.forest }, current: { alignItems: 'center', backgroundColor: '#FFFFFF99', borderRadius: 99, height: 26, justifyContent: 'center', position: 'absolute', right: 24, top: 23, width: 26 }, currentDot: { backgroundColor: '#4A9DFF', borderColor: colors.white, borderRadius: 99, borderWidth: 3, height: 13, width: 13 }, mapLabel: { backgroundColor: colors.white, borderRadius: radius.md, bottom: 16, left: 16, padding: spacing.md, position: 'absolute', right: 16 }, mapLabelTitle: { color: colors.ink, ...typography.label }, mapLabelBody: { color: colors.inkSoft, marginTop: 2, ...typography.caption }, cardRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.md }, iconBubble: { alignItems: 'center', backgroundColor: colors.forestSoft, borderRadius: radius.md, height: 42, justifyContent: 'center', width: 42 }, cardCopy: { flex: 1 }, cardTitle: { color: colors.ink, ...typography.heading }, cardBody: { color: colors.inkSoft, marginTop: 3, ...typography.caption } });
